dist: xenial
cache: pip
branches:
  only:
  - master
  - develop
  # https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
  # safe list can prevent tag building, add rexp to detect tag
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

language: python
python:
- 3.6
- 3.7

install:
- pip install --upgrade pip
- pip install tensorflow==2.0.0-rc1
- python setup.py -q install

script:
- python setup.py -q test
